### ISSUE TITLE
Alternaiva para o patch do xdg-open

### ISSUE THREAD

**Issue by farribeiro** [flathub/br.gov.fazenda.receita.irpf2023#2]
Estava comentando com um javeiro e questionei o que poderia ser feito e ele me responde

> @farribeiro unica coisa q eu alteraria ali seria fechar o stream de saída e jaz

Abraços

Link to https://github.com/flathub/br.gov.fazenda.receita.irpf/issues/53 https://github.com/flathub/br.gov.fazenda.receita.irpf/issues/54

**Comment by guihkx** [comment]
Eu não tenho certeza se entendi o que ele quis dizer com isso. Ou, mais precisamente, não entendi como que ele disse seria uma alternativa ao patch em questão... 🤷 

O ideal seria ele abrir um pull request com a ideia dele.

**Comment by farribeiro** [comment]
![image](https://user-images.githubusercontent.com/198756/236356064-5884c831-a4a0-4d56-9dc1-e1c9aaeb1254.png)


Vou fechar por não ter uma solução, somente a ideia
